spring.application.name=cloudvmx-backend

# Server Configuration
server.port=8080
server.servlet.context-path=/

# Logging
logging.level.root=INFO
logging.level.com.luxman.cloudvmx_backend=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# CORS Configuration
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=*
spring.web.cors.allowed-headers=*

# Docker Configuration
docker.host=${DOCKER_HOST:}

# Application Info
app.name=CloudVMX Backend
app.version=0.0.1

# Apache Guacamole Configuration
guacamole.url=${GUACAMOLE_URL:http://localhost:8080/guacamole}
