@echo off
setlocal

echo ==================================================
echo   CloudVMX Unified Multi-OS Hub (RustDesk Server)
echo ==================================================
echo.

REM Start the Docker Compose stack
echo Starting the RustDesk Server components...
docker-compose up -d

REM Wait a moment for the keys to be generated by hbbs if they don't exist
timeout /t 5 /nobreak >nul

echo.
echo ==================================================
echo                  SERVER STATUS
echo ==================================================
echo RustDesk Web Client Gateway: http://localhost:5000
echo RustDesk ID Server (hbbs)  : Listening on port 21116
echo RustDesk Relay (hbbr)      : Listening on port 21117
echo ==================================================
echo.
echo [IMPORTANT: CLIENT CONFIGURATION KEY]
echo Copy this Public Key and enter it in all your devices
echo (Windows, Kali, Android) under Settings -^> Network -^> Key:
echo.

if exist "data\id_ed25519.pub" (
    type "data\id_ed25519.pub"
    echo.
) else (
    echo [ERROR] The key file was not found. Ensure Docker is running.
)

echo.
pause
